name: Deploy Identity Service to Render with Docker

on:
  push:
    branches:
      - main  # Trigger when commits are pushed to the main branch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-app:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-app:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      # Step 6: Log in to Render
      - name: Log in to Render
        run: |
          echo ${{ secrets.RENDER_API_KEY }} | curl -X POST https://api.render.com/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"serviceId": "identity-service"}'

      # Step 7: Deploy image from Docker Hub to Render
      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/services/identity-service/deployments \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"image": "${{ secrets.DOCKER_USERNAME }}/identity-app:latest"}'
